language: ruby
before_install:
  - gem install bundler
  - mysql -e 'CREATE DATABASE papyrus_test;'
rvm:
  - "2.4.5"
env:
  - DB=sqlite
  - DB=mysql
bundler_args: --without development
script:
  - RAILS_ENV=test bin/rails db:migrate --trace
  - RAILS_ENV=test bin/rails db:test:prepare
  - RAILS_ENV=test bin/rails test test/models
  - RAILS_ENV=test bin/rails test test/controllers
before_script:
  - cp config/travis.database.yml config/database.yml
services:
  - mysql
