language: ruby
rvm:
  - "2.4.1"
  - "2.3.1"
env:
  - DB=sqlite
  - DB=mysql
bundler_args: --without development
script:
  - RAILS_ENV=test bin/rails db:migrate --trace
  - RAILS_ENV=test bin/rails db:test:prepare
  - RAILS_ENV=test bin/rails test test/models
  - RAILS_ENV=test bin/rails test test/controllers
before_script:
  - cp config/travis.database.yml config/database.yml
  - mysql -e 'create database papyrus_test'
