version: '3.6'
services:
  web:
    build:
      context: .
      args:
        - NODE_VER=${NODE_VER:-lts}
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed && bundle exec rake assets:precompile && rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    ports:
      - ${PORT:-4004}:${PORT:-4004}
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=${PORT:-4004}
      - RAILS_ENV=${RAILS_ENV:-development}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=mysql2://root:mypasswd@db/${COMPOSE_PROJECT_NAME}_${RAILS_ENV:-development}
      - TEST_DATABASE_URL=sqlite3:db/test.sqlite3
      - RAILS_SERVE_STATIC_FILES=true
      - NODE_OPTIONS=--openssl-legacy-provider
      - SELENIUM_SERVER=chrome-server
    env_file:
      - path: ./override.env
        required: false

  db:
    image: mysql
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: mypasswd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  mail:
    image: dockage/mailcatcher
    ports:
      - ${MAILCATCHER_HTTP:-4084}:1080

  chrome-server:
    image: selenium/standalone-chrome:96.0
    ports:
      - ${VNC_HTTP:-7904}:7900

